export const AdvisorIntent = {
  REVIEW_MAJOR: "REVIEW_MAJOR",
  COMPARE_MAJORS: "COMPARE_MAJORS",
  COMPARE_SCHOOLS: "COMPARE_SCHOOLS",
  ADMISSION_CHANCE: "ADMISSION_CHANCE",
  SCORE_SUGGESTION: "SCORE_SUGGESTION",
  SCORE_CALCULATION: "SCORE_CALCULATION",
  TUITION: "TUITION",
  CAREER_PATH: "CAREER_PATH",
  PERSONAL_FIT: "PERSONAL_FIT",
  STUDY_PLAN: "STUDY_PLAN",
  LATEST_ADMISSION_INFO: "LATEST_ADMISSION_INFO",
  GENERAL_ADVICE: "GENERAL_ADVICE",
  UNKNOWN: "UNKNOWN",
} as const;

export type AdvisorIntent = (typeof AdvisorIntent)[keyof typeof AdvisorIntent];

export const ADVISOR_INTENTS = Object.values(AdvisorIntent);
