export type AofAdmissionMethodTag = "PT1" | "PT2" | "PT3";
export type AofCombinationCode = "A00" | "A01" | "D01" | "D07" | "X06" | "X26";
export type AofCampus = "MB_HANOI" | "MN_HCMC" | "MB_HOALAC";

export type AofProgram2026 = {
  sourceSheet: string;
  campus: AofCampus;
  programCode2026: string;
  programName: string;
  majorCode: string;
  majorName: string;
  quota: number;
  methods: AofAdmissionMethodTag[];
  combinations: AofCombinationCode[];
};

const METHODS_ALL: AofAdmissionMethodTag[] = ["PT1", "PT2", "PT3"];
const COMBO_CCQT: AofCombinationCode[] = ["A01", "D01", "D07", "X26"];
const COMBO_STANDARD: AofCombinationCode[] = ["A00", "A01", "D01", "D07", "X06", "X26"];

/**
 * Program catalog for AOF admission year 2026.
 * Source: E:/zpath/aof/TUYEN_SINH_2026_HOC_VIEN_TAI_CHINH.xlsx
 */
export const AOF_PROGRAMS_2026: AofProgram2026[] = [
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC12.01QT",
    programName: "Kinh tế đầu tư (Theo định hướng ACCA)",
    majorCode: "7310104",
    majorName: "Kinh tế đầu tư",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC03.01QT",
    programName: "Quản trị doanh nghiệp (Theo định hướng ICAEW CFAB)",
    majorCode: "7340101",
    majorName: "Quản trị kinh doanh",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC11.02QT",
    programName: "Digital Marketing (Theo định hướng ICDL)",
    majorCode: "7340115",
    majorName: "Marketing",
    quota: 200,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC09.01QT",
    programName: "Thẩm định giá và kinh doanh bất động sản (Theo định hướng ACCA)",
    majorCode: "7340116",
    majorName: "Bất động sản",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC15.01QT",
    programName: "Kinh doanh quốc tế (Theo định hướng ICAEW CFAB)",
    majorCode: "7340120",
    majorName: "Kinh doanh quốc tế",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.01QT",
    programName: "Thuế và Quản trị thuế (Theo định hướng ACCA)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.06QT",
    programName: "Hải quan và Logistics (Theo định hướng FIATA)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 370,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.09QT",
    programName: "Phân tích tài chính (Theo định hướng ICAEW CFAB)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 240,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.11QT",
    programName: "Tài chính doanh nghiệp (Theo định hướng ACCA)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 370,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.15QT",
    programName: "Ngân hàng (Theo định hướng ICAEW CFAB)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.19QT",
    programName: "Đầu tư tài chính (Theo định hướng ICAEW CFAB)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC02.01QT",
    programName: "Kế toán doanh nghiệp (Theo định hướng ACCA)",
    majorCode: "7340301",
    majorName: "Kế toán",
    quota: 350,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC02.02QT",
    programName: "Kế toán quản trị và Kiểm soát quản lý (Theo định hướng CMA)",
    majorCode: "7340301",
    majorName: "Kế toán",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC02.03QT",
    programName: "Kế toán công (Theo định hướng ACCA)",
    majorCode: "7340301",
    majorName: "Kế toán",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC10.01QT",
    programName: "Kiểm toán (Theo định hướng ICAEW CFAB)",
    majorCode: "7340302",
    majorName: "Kiểm toán",
    quota: 370,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC05.01",
    programName: "Tiếng Anh tài chính kế toán",
    majorCode: "7220201",
    majorName: "Ngôn ngữ Anh",
    quota: 160,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC06.01",
    programName: "Kinh tế và quản lý nguồn lực tài chính",
    majorCode: "7310101",
    majorName: "Kinh tế",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC16.01",
    programName: "Kinh tế chính trị - Tài chính",
    majorCode: "7310102",
    majorName: "Kinh tế chính trị",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC12.01",
    programName: "Kinh tế đầu tư",
    majorCode: "7310104",
    majorName: "Kinh tế đầu tư",
    quota: 150,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC18.01",
    programName: "Toán tài chính",
    majorCode: "7310108",
    majorName: "Toán kinh tế",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC03.12",
    programName: "Quản trị doanh nghiệp; Quản trị kinh doanh du lịch",
    majorCode: "7340101",
    majorName: "Quản trị kinh doanh",
    quota: 160,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC11.01",
    programName: "Marketing",
    majorCode: "7340115",
    majorName: "Marketing",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC09.01",
    programName: "Thẩm định giá và kinh doanh bất động sản",
    majorCode: "7340116",
    majorName: "Bất động sản",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.01",
    programName:
      "Tài chính - Ngân hàng 1 (Thuế; Hải quan và Nghiệp vụ ngoại thương; Tài chính quốc tế)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 350,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.02",
    programName: "Tài chính - Ngân hàng 2 (Tài chính doanh nghiệp; Phân tích tài chính)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 300,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC01.03",
    programName: "Tài chính - Ngân hàng 3 (Ngân hàng; Đầu tư tài chính)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 180,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC08.01",
    programName: "Tài chính bảo hiểm",
    majorCode: "7340204",
    majorName: "Bảo hiểm",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC02.13",
    programName: "Kế toán doanh nghiệp; Kế toán công",
    majorCode: "7340301",
    majorName: "Kế toán",
    quota: 550,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC10.01",
    programName: "Kiểm toán",
    majorCode: "7340302",
    majorName: "Kiểm toán",
    quota: 200,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC07.01",
    programName: "Quản lý hành chính",
    majorCode: "7340403",
    majorName: "Quản lý công",
    quota: 140,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC04.01",
    programName: "Hệ thống thông tin tài chính kế toán",
    majorCode: "7340405",
    majorName: "Hệ thống thông tin quản lý",
    quota: 90,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC17.01",
    programName: "Luật kinh doanh",
    majorCode: "7380101",
    majorName: "Luật",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC16.01/05",
    programName: "Khoa học dữ liệu trong tài chính",
    majorCode: "7460108",
    majorName: "Khoa học dữ liệu",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC13.01",
    programName: "Trí tuệ nhân tạo trong tài chính kế toán",
    majorCode: "7480201",
    majorName: "Công nghệ thông tin",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MB - ĐH CCQT",
    campus: "MB_HANOI",
    programCode2026: "HC.DDP",
    programName: "Chương trình LKĐT mỗi bên cấp Một Bằng cử nhân DDP (Dual Degree Programme)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 120,
    methods: METHODS_ALL,
    combinations: COMBO_STANDARD,
  },
  {
    sourceSheet: "MN - TP.HCM",
    campus: "MN_HCMC",
    programCode2026: "HS01.06QT",
    programName: "Hải quan và Logistics (Theo định hướng FIATA)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 100,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MN - TP.HCM",
    campus: "MN_HCMC",
    programCode2026: "HS01.09QT",
    programName: "Phân tích tài chính (Theo định hướng ICAEW CFAB)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 50,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MN - TP.HCM",
    campus: "MN_HCMC",
    programCode2026: "HS01.11QT",
    programName: "Tài chính doanh nghiệp (Theo định hướng ACCA)",
    majorCode: "7340201",
    majorName: "Tài chính - Ngân hàng",
    quota: 100,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MN - TP.HCM",
    campus: "MN_HCMC",
    programCode2026: "HS02.01QT",
    programName: "Kế toán doanh nghiệp (Theo định hướng ACCA)",
    majorCode: "7340301",
    majorName: "Kế toán",
    quota: 80,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
  {
    sourceSheet: "MN - TP.HCM",
    campus: "MN_HCMC",
    programCode2026: "HS10.01QT",
    programName: "Kiểm toán (Theo định hướng ICAEW CFAB)",
    majorCode: "7340302",
    majorName: "Kiểm toán",
    quota: 50,
    methods: METHODS_ALL,
    combinations: COMBO_CCQT,
  },
];
